### ISSUE TITLE
Getting error while executing command 

### ISSUE THREAD

**Issue by priyadesai23** [mahurtado/oracle2couchbase#2]
Hi,

I am facing error while trying to use oracle2couchbase tool

[root@ilvpbg1013 oracle]# java -cp /oravl01/couchbase/oracle2couchbase.jar:/oravl01/couchbase/couchbase-java-client-2.2.8.jar:/oravl01/couchbase/couchbase-core-io-1.2.9.jar:/oravl01/couchbase/rxjava-1.0.17.jar:/oravl01/oracle/12.1.0.2/jdbc/lib/ojdbc6.jar  -DcbClusterAddress=10.234.90.149 -DcbBucketName=default -DoraAddress=10.234.90.149 -DoraUser=PRDPRIYAAPP2 -DoraPassword=PRDPRIYAAPP2 -DoraService=PMX4DB -DoraTables=SMM1_SEARCHFAVORITES com.oracle2couchbase.Loader
Error: Could not find or load main class com.oracle2couchbase.Loader

Please let me know how can i solve this 

Thanks
Priyadarshani Desai

**Comment by priyadesai23** [comment]
Hi,


Do we have step by step document how to use this tool ?

Thanks
Priyadarshani Desai

**Comment by rohailnasir** [comment]
Same issue on my side

**Comment by kamal141** [comment]
[oracle@couchbasehost oracle2couchbase]$ java -cp ./oracle2couchbase.jar:./u01/app/oracle/ggaa/oracle2couchbase/couchbase-java-client-2.2.6.jar:./u01/app/oracle/ggaa/oracle2couchbase/couchbase-core-io-1.2.7.jar:./u01/app/oracle/ggaa/oracle2couchbase/rxjava-1.0.17.jar:./u01/app/oracle/ggaa/oracle2couchbase/ojdbc6.jar -DcbClusterAddress=xxx.59.77.5 -DcbBucketName=HR -DoraAddress=xxx59.90.225 -DoraUser=HR -DoraPassword=hr -DoraService=orcl -DoraTables=COUNTRIES,DEPARTMENTS,EMPLOYEES,JOBS,JOB_HISTORY,LOCATIONS,REGIONS com.oracle2couchbase.Loader
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/couchbase/client/java/document/Document
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.couchbase.client.java.document.Document
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
[oracle@couchbasehost oracle2couchbase]

**Comment by feschber** [comment]
Same here, it only runs in eclipse but not in cmd
