### ISSUE TITLE
Getting DocumentAlreadyExistsException on initial conversion, no PK the cause?

### ISSUE THREAD

**Issue by davidmichaelkarr** [mahurtado/oracle2couchbase#5]
I've barely gotten started learning about Couchbase (very familiar with Oracle). I need to convert an Oracle DB to Couchbase, so this seems appropriate.

After I got all my jars and parameters set up, in addition to creating a user with the same name as the bucket (this tool was apparently written with 4.x in mind, and I'm using 5.x, which doesn't have passwords on buckets), when I finally got it running, I saw exceptions like the following:

```
SEVERE: Error processing row. key: xxxxxxxx
com.couchbase.client.java.error.DocumentAlreadyExistsException
	at com.couchbase.client.java.CouchbaseAsyncBucket$13.call(CouchbaseAsyncBucket.java:470)
	at com.couchbase.client.java.CouchbaseAsyncBucket$13.call(CouchbaseAsyncBucket.java:454)
```
Looking through the tool documentation, I see that it says it uses the PK of the table.  Unfortunately, I have a situation where most of my tables don't have a PK defined.  I have a feeling this error is because of that.  What is a reasonable path forward to resolving this?

**Comment by davidmichaelkarr** [comment]
I imagine a possible but nasty workaround would simply be to consider all the columns as the composite PK.  I guess I'll see if that works and perhaps file a PR if it does.
